### ISSUE TITLE
Extend project

### ISSUE THREAD

**Issue by himanshu-1495** [abhi24gupta/EmployeeManagementSpringBoot#1]
First off great work. 

Some things I wanted to highlight.

Unit tests look fine for now but are too trivial. As you add more business logic you will need more tests. 
Write some sample unit tests for Controller Layer separately even if Controllers don't contain business logic as that will help you to learn the testing APIs used for controller layer tests.
Same goes for dao layer as well.

Use only @Data annotation from lombok no need to add getters setters then in your entities. Also I belive you have incorrectly used @Autowired in your Employee Entity. That is used for autowiring beans(such as your service class, repository class which are singletons) managed by the Spring Container not for entities. 
Or if there is a specific reason to use that annotation please mention that.

Add more entities to this Employee Management System. Minimum requirements are as given to you in the assignment but also be creative and add entities to support more business use cases. 
Eg- System should be capable of storing Personal Details of employee, Qualifications, Work Ex, etc. Right now it is too simple with only Employee and Department. Add task tracking for each employee as well.
Once you have finalized a schema then upload the schema here and also add the new entities to the code.
Then create the APIs to support ALL possible business transactions on your schema, eg finding all the employees under a particular manager. Mention the time complexity of each of the operations.
Mention these in the README.md of your project. Use proper markdown while creating the readme.

**Comment by abhi24gupta** [comment]
Thanks for review.

Things added now :
1. Used @DaTa annotation from Lombok and removed the getters & setters.
2. @Autowired in Employee Entity is done to do the dependency Injection of the Department Entity. (I think so)
3. Added two more Entities named Leave and Salary.(Just a start, will look further to add security to them so that they are not accessible easily)
4. Also, updated the Employee and Department entity adding some more attributes.
5. Some more work is still pending. Will Update soon.
